Try with different dockerfile

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -106,97 +106,98 @@ jobs:
             echo "BUILD=false" | tee -a "$GITHUB_ENV"
           fi
 
-      - name: Find required base image version
-        run: |
-          git init >/dev/null 2>&1
-          git remote add source-base "${{ env.BASE_IMAGE_REMOTE_REPOSITORY }}" >/dev/null 2>&1
-          BASE_IMAGE_VERSION=$(git ls-remote --exit-code source-base HEAD | awk '{ print $1 }')
+      # - name: Find required base image version
+        # run: |
+          # git init >/dev/null 2>&1
+          # git remote add source-base "${{ env.BASE_IMAGE_REMOTE_REPOSITORY }}" >/dev/null 2>&1
+          # BASE_IMAGE_VERSION=$(git ls-remote --exit-code source-base HEAD | awk '{ print $1 }')
 
-          if [ -z "$BASE_IMAGE_VERSION" ]; then
-            echo "Unable to find base image version"
-            exit 1
-          fi
+          # if [ -z "$BASE_IMAGE_VERSION" ]; then
+            # echo "Unable to find base image version"
+            # exit 1
+          # fi
 
-          echo "BASE_IMAGE_VERSION=${BASE_IMAGE_VERSION}" | tee -a "$GITHUB_ENV"
+          # echo "BASE_IMAGE_VERSION=${BASE_IMAGE_VERSION}" | tee -a "$GITHUB_ENV"
 
-      - name: Check if base image needs to be built
-        if: env.BUILD == 'true'
-        run: |
-          BUILD='true'
-          if [ "${{ github.event.inputs.force-build }}" != "true" ]; then
-            VERSION_DATETIME=$(curl -s https://registry.hub.docker.com/v2/repositories/${{ env.BASE_IMAGE_NAME }}/tags | \
-              jq -r '.results | map(select(.name == "${{ env.BASE_IMAGE_VERSION }}")) | map(.tag_last_pushed) | .[]')
+      # - name: Check if base image needs to be built
+        # if: env.BUILD == 'true'
+        # run: |
+          # BUILD='true'
+          # if [ "${{ github.event.inputs.force-build }}" != "true" ]; then
+            # VERSION_DATETIME=$(curl -s https://registry.hub.docker.com/v2/repositories/${{ env.BASE_IMAGE_NAME }}/tags | \
+              # jq -r '.results | map(select(.name == "${{ env.BASE_IMAGE_VERSION }}")) | map(.tag_last_pushed) | .[]')
 
-            if [ -n "$VERSION_DATETIME" ]; then
-              echo "Base image version was previously pushed at ${VERSION_DATETIME}"
-              BUILD='false'
-            fi
-          fi
+            # if [ -n "$VERSION_DATETIME" ]; then
+              # echo "Base image version was previously pushed at ${VERSION_DATETIME}"
+              # BUILD='false'
+            # fi
+          # fi
 
-          echo "BASE_IMAGE_BUILD=${BUILD}" | tee -a "$GITHUB_ENV"
+          # echo "BASE_IMAGE_BUILD=${BUILD}" | tee -a "$GITHUB_ENV"
 
 
-  build-and-push-base-image:
-    name: Build and push base image
-    runs-on: ubuntu-latest
+  # build-and-push-base-image:
+    # name: Build and push base image
+    # runs-on: ubuntu-latest
 
-    needs:
-      - prepare-environment
+    # needs:
+      # - prepare-environment
 
-    if: needs.prepare-environment.outputs.base_image_build == 'true'
+    # if: needs.prepare-environment.outputs.base_image_build == 'true'
 
-    permissions:
-      contents: read
-      packages: write
+    # permissions:
+      # contents: read
+      # packages: write
 
-    env:
-      BASE_IMAGE_NAME: ${{ needs.prepare-environment.outputs.base_image_name }}
-      BASE_IMAGE_VERSION: ${{ needs.prepare-environment.outputs.base_image_version }}
+    # env:
+      # BASE_IMAGE_NAME: ${{ needs.prepare-environment.outputs.base_image_name }}
+      # BASE_IMAGE_VERSION: ${{ needs.prepare-environment.outputs.base_image_version }}
 
-    steps:
-      - name: Checkout current repo
-        uses: actions/checkout@v3
+    # steps:
+      # - name: Checkout current repo
+        # uses: actions/checkout@v3
 
-      - name: Checkout version from source
-        run: |
-          git remote add source "${{ env.BASE_IMAGE_REMOTE_REPOSITORY }}"
-          git fetch source ${{ env.BASE_IMAGE_VERSION }}
-          git checkout ${{ env.BASE_IMAGE_VERSION }}
+      # - name: Checkout version from source
+        # run: |
+          # git remote add source "${{ env.BASE_IMAGE_REMOTE_REPOSITORY }}"
+          # git fetch source ${{ env.BASE_IMAGE_VERSION }}
+          # git checkout ${{ env.BASE_IMAGE_VERSION }}
 
-      - name: Log in to the Container registry
-        uses: docker/login-action@v2
-        with:
-          username: ${{ env.REGISTRY_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      # - name: Log in to the Container registry
+        # uses: docker/login-action@v2
+        # with:
+          # username: ${{ env.REGISTRY_USERNAME }}
+          # password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Extract metadata (tags, labels) for Docker
-        id: meta
-        uses: docker/metadata-action@v4
-        with:
-          flavor: |
-            latest=true
-          tags: |
-            type=raw,value=${{ env.BASE_IMAGE_VERSION }}
-          images: ${{ env.BASE_IMAGE_NAME }}
+      # - name: Extract metadata (tags, labels) for Docker
+        # id: meta
+        # uses: docker/metadata-action@v4
+        # with:
+          # flavor: |
+            # latest=true
+          # tags: |
+            # type=raw,value=${{ env.BASE_IMAGE_VERSION }}
+          # images: ${{ env.BASE_IMAGE_NAME }}
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
+      # - name: Set up QEMU
+        # uses: docker/setup-qemu-action@v2
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+      # - name: Set up Docker Buildx
+        # uses: docker/setup-buildx-action@v2
 
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v3
-        with:
-          context: .
-          file: ./build/Dockerfile
-          platforms: |
-            linux/arm/v7
-          push: true
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
+      # - name: Build and push Docker image
+        # uses: docker/build-push-action@v3
+        # with:
+          # context: .
+          # file: ./build/Dockerfile
+          # platforms: |
+            # linux/arm/v7
+          # push: true
+          # tags: ${{ steps.meta.outputs.tags }}
+          # labels: ${{ steps.meta.outputs.labels }}
+          # cache-from: type=gha
+          # cache-to: type=gha,mode=max
+
 
   build-and-push:
     name: Build and push
@@ -204,9 +205,10 @@ jobs:
 
     needs:
       - prepare-environment
-      - build-and-push-base-image
+      # - build-and-push-base-image
 
-    if: "!cancelled() && needs.prepare-environment.outputs.build == 'true'"
+    if: needs.prepare-environment.outputs.build == 'true'
+    # if: "!cancelled() && needs.prepare-environment.outputs.build == 'true'"
 
     permissions:
       contents: read
@@ -227,10 +229,13 @@ jobs:
           git checkout ${{ env.VERSION }}
 
           # Replace the base image
-          sed -i 's#registry.gitlab.com/hydroqc/hydroqc-base-container/3.11:latest@sha256:[^ ]*#thexaf/hydroqc-base-container:${{ env.BASE_IMAGE_VERSION }}#g' Dockerfile
+          # sed -i 's#registry.gitlab.com/hydroqc/hydroqc-base-container/3.11:latest@sha256:[^ ]*#thexaf/hydroqc-base-container:${{ env.BASE_IMAGE_VERSION }}#g' Dockerfile
 
           # Check the diff
-          git diff
+          # git diff
+
+          # Replace Dockerfile
+          git show main:Dockerfile > Dockerfile
 
       - name: Log in to the Container registry
         uses: docker/login-action@v2
